function drawData(x1,x2,y1,y2,plotData,labelsData)
    file = io.open("plot_script.plt","w")
    io.output(file)
    io.write(string.format("set xrange [%d:%d]\n",x1-2,x2+2))
    io.write(string.format("set yrange [%d:%d]\n",y1-2,y2+2))
    io.write("set grid\n")
    io.write(string.format("plot '%s' using 1:2:3:4 with vectors nohead notitle, \\\n",plotData))
    --io.write(string.format("\t'%s' using 2:3:(sprintf(\"%s\",$1)) with labels point pt 7 offset char 0,0.5 notitle\n",labelsData,"%d"))
    
    --io.write(string.format("stats '%s' using 1:2 nooutput\n",labelsData))
    --io.write("do for [i=0:STATS_records-1] {\n")
    --    io.write(string.format("\tCMD=sprintf(\"sed -n '%sp' %s\",i+1)\n","%d",labelsData))
    --    io.write("\tXY=system(CMD)\n")
    --    io.write("\tif (strlen(XY) > 0){\n")
    --        io.write("\t\tX=real(word(XY,1))\n")
    --        io.write("\t\tY=real(word(XY,2))\n")
    --        io.write("\t\tif (X!=NaN && Y!=NaN){\n")
    --            io.write("\t\t\tset label sprintf(\"%d %.2f %.2f\",i+1, X, Y) at X,Y offset 0.5, 0.5 textcolor rgb \"black\"\n")
    --        io.write("\t\t}\n")
    --    io.write("\t}\n")
    --io.write("}\n")
    
    io.close(file)
    os.execute("gnuplot -persist plot_script.plt")
end